name: GitHub Pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
      # You may pin to the exact commit or the version.
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          # Build directory to deploy
          build_dir: "./build"

on:
  push: 
    branches: [ master ]
